---
- include:              '../tasks/create_files.yml'

- copy:
    src:                'files/bin/update_steam'
    dest:               '/usr/local/bin/update_steam'
    mode:               '0755'
    owner:              'root'
    group:              'root'

- template:
    src:                'templates/cron.d/update_steam.j2'
    dest:               '/etc/cron.d/update_steam'
    mode:               '0644'
    owner:              'root'
    group:              'root'
