---
- include_vars: "../../../../sensitive/ansible/host_vars/{{steamcmd_server}}.yml"
- include: packages.yml
- include: user.yml
  when: steamcmd_create_user
- include: setup.yml
  become: yes
  become_user: '{{ steamcmd_user }}'
