---
- include_vars: "../../../sensitive-ansible/inventory/host_vars/{{ inventory_hostname }}.yml"
- include: packages.yml
- include: user.yml
  when: steamcmd_create_user
- include: setup.yml
  become: yes
  become_user: '{{ steamcmd_user }}'
  become_method: 'sudo'
- include: automatic_updates.yml
  become: yes
