---

- name: update the apt package index
  gather_facts: True
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: update the yum package index
  gather_facts: True
  yum:
    name: '*'
    state: latest
  when: ansible_pkg_mgr == 'yum'

- include_vars: '{{ item }}'
  with_first_found:
    - '../vars/{{ ansible_os_family }}-{{ ansible_userspace_bits }}.yml'
    - '../vars/{{ ansible_os_family }}.yml'
    - '../vars/Debian.yml'

- name: install packages
  package:
    name: '{{ item }}'
    state: present
  with_items: "{{steamcmd_packages}}"
